leftnav:
- identifier: c3f911f7-7656-2ccd-d646-51b79d84626a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: fb96e699-da99-0156-6524-fa612a364e43
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 6e0e8fb8-e84e-e8a8-6e86-a87a3d88fcd9
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 104893c7-980e-b3ba-6a64-cd1ac205f903
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 673e8610-0aa0-6e06-b20b-f2dc71de2203
  name: Projects
  url: /pages/projects
  weight: 50
